import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/index.module.scss'

// a lot of the brand colors come from the official websites

import { AiFillLinkedin } from 'react-icons/ai'
import { FaGithubSquare, FaYoutubeSquare } from 'react-icons/fa'

export default function Home() {
  return (
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id={styles['header']}>
          <nav id={styles['main-nav']}>
            <Link href="/blog">
              <h5 className={`${styles['nav-item']} ${styles['blog-text-gradient']}`}>Blog</h5>
            </Link>
            <Link href="/about">
              <h5 className={`${styles['nav-item']} ${styles['about-text-gradient']}`}>About me</h5>
            </Link>
          </nav>

          {/* https://stackoverflow.com/a/65509211/17712310 */}
          <img 
            src="/avatar.png"
            alt="Avatar image"
            id={styles['avatar-image']}
          />
        </div>


        <div id={styles['section-1-wrapper']}>
          <p id={styles['about-me-short-desc']}>Hi, I'm Clay. I'm a web developer out of Northeast Ohio.</p>

          <div id={styles['social-quick-links']}>
            {/* https://react-icons.github.io/react-icons */}
            <AiFillLinkedin id={styles['linked-in-social-quick-link']} className={styles['social-quick-link']} />
            <FaGithubSquare id={styles['github-social-quick-link']} className={styles['social-quick-link']} />
            <FaYoutubeSquare id={styles['youtube-social-quick-link']} className={styles['social-quick-link']} />
          </div>
        </div>
      </main>
      </>
  )
}
