import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/index.module.scss'

import { useInView } from 'react-intersection-observer'

// a lot of the brand colors come from the official websites

import { AiFillLinkedin } from 'react-icons/ai'
import { FaGithubSquare, FaYoutubeSquare } from 'react-icons/fa'

export default function Home() {

  // https://youtu.be/r1auJEf9ISo
  // https://github.com/thebuilder/react-intersection-observer
  const { ref: descRef, inView: descInView, entry: descEntry } = useInView({
    threshold: 1,
    // https://youtu.be/T8EYosX4NOo
    rootMargin: '0px 0px -20% 0px',
    triggerOnce: true
  })





  return (
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id={styles['header']}>
          <nav id={styles['main-nav']}>
            <Link href="/blog">
              <h5 className={`${styles['nav-item']} ${styles['blog-text-gradient']}`}>Blog</h5>
            </Link>
            <Link href="/about">
              <h5 className={`${styles['nav-item']} ${styles['about-text-gradient']}`}>About me</h5>
            </Link>
          </nav>

          {/* https://stackoverflow.com/a/65509211/17712310 */}
          <img 
            src="/avatar.png"
            alt="Avatar image"
            id={styles['avatar-image']}
          />
        </div>

        Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, magnam. Similique quas accusamus tempora officiis? Exercitationem commodi, et neque temporibus eveniet cum eligendi ad tempore! Aspernatur neque doloremque sed velit aliquid doloribus, veniam totam rerum distinctio fugit expedita sit. Nam quasi eaque quaerat ex magni fuga veniam corrupti praesentium possimus? Dolorum odio explicabo ipsa laboriosam exercitationem distinctio, quaerat tenetur. Repellendus excepturi debitis in iste sunt laborum nobis assumenda voluptatum, laboriosam reiciendis quasi omnis dicta iure cumque porro quisquam vel delectus sed quod. Sed labore dignissimos, nostrum nemo molestias facere numquam. Eligendi dolores expedita, nobis porro culpa ipsam dolorum, error sint quisquam maxime quasi eius. Eaque optio quas provident deserunt nemo quia officia pariatur animi beatae voluptatibus aliquid quidem assumenda similique nihil tenetur exercitationem delectus, molestias est officiis sequi. Dolores, mollitia? Est quod sit, officiis velit vel eaque? Ullam labore itaque fugiat repellat, rerum rem aliquid excepturi asperiores placeat et porro perspiciatis aspernatur nisi mollitia non. Odio asperiores delectus eveniet quae, excepturi modi quasi suscipit quod dolorum adipisci, magni nisi, natus animi amet dignissimos expedita sapiente autem fuga. Earum ab sunt similique laboriosam aliquid fugit repellendus animi dolore tempore odit, nihil rerum itaque. Distinctio error dolore enim inventore aut, ea incidunt? Nihil soluta necessitatibus error impedit eligendi eum iste non aliquam quas ad maiores minima cupiditate nulla voluptatibus, commodi dolorum fugiat repellendus sunt. Commodi vitae numquam at esse, eum odit! Modi atque saepe voluptatem, facere ullam sint accusamus nesciunt sequi sed repellendus voluptatum libero vitae, quibusdam totam eum quas esse assumenda repudiandae, eius excepturi architecto! Cumque doloribus eum ad quisquam, in excepturi vero veniam, laudantium ipsa, quam saepe asperiores mollitia sapiente. Perspiciatis eius veritatis quas laborum! Hic, est numquam officiis exercitationem voluptate nesciunt incidunt aperiam dolorem laudantium eum tempora enim quibusdam veniam, officia ex ratione cumque sed sapiente nam, laboriosam nihil! Reprehenderit maiores voluptate eos numquam labore quos velit, nemo alias impedit quas delectus saepe tempore vel! Eaque quas, incidunt itaque quo tempora nisi quaerat quos enim qui, repudiandae quisquam labore quia? Doloremque, suscipit cupiditate. Accusantium iure quod nihil est reiciendis cumque veritatis officiis ipsum repudiandae? Nostrum quas aliquid error? Aliquid, quis rem fugit in necessitatibus laboriosam itaque ratione commodi minima quisquam mollitia laborum natus animi! Quis laboriosam sit labore alias itaque animi, ipsa qui molestiae maiores impedit aliquam. Nostrum illo voluptatibus hic eum doloribus nam, quisquam dolorem, velit ipsam cum dignissimos aliquam ex ratione accusantium, excepturi ut eaque? Provident consequuntur explicabo, rerum iste optio laboriosam ex nulla amet voluptatum dolores nihil impedit accusantium nisi ab recusandae culpa. Sequi, voluptatem natus optio qui omnis pariatur a iusto aspernatur aliquid voluptas, quisquam quo quis, eveniet reiciendis placeat aut eos assumenda nam praesentium veniam blanditiis ipsa? Quas velit earum laboriosam minus commodi quisquam recusandae molestias? Atque doloribus quos eius vel voluptates, ea praesentium eligendi sed, porro ab quod ipsa a vero dolorem molestiae, modi quis veritatis laborum? Vero, tenetur hic repellendus ea aut delectus aspernatur necessitatibus reiciendis inventore quisquam amet cupiditate officia earum dolorem voluptate. Quidem, veritatis, eum praesentium, minus rerum adipisci ullam maiores quam ea quis distinctio! Ipsum veniam, repellat quidem eum expedita quasi consequatur? Eligendi ab optio sed odio tempore consequuntur ut dolore quibusdam? Voluptatibus qui dolorum assumenda nesciunt omnis eos. Modi, molestiae fuga, ea natus ipsam doloribus dolorem fugit sequi inventore veniam voluptates voluptatem nostrum cupiditate dolore vero laboriosam eos impedit molestias. Dignissimos blanditiis consectetur consequuntur corrupti fuga, aspernatur laboriosam corporis repellat vel debitis, illo explicabo obcaecati aliquam similique odio nobis laborum accusamus voluptas expedita voluptatibus quas eligendi reiciendis harum inventore? Cum quam id, nisi suscipit, dicta culpa illum sunt voluptate cupiditate maxime vero atque autem quis fuga molestias, optio officiis. Alias quis deserunt, soluta enim inventore sit aperiam tempora sunt at officia dolore suscipit voluptas perspiciatis minima eveniet ipsa totam accusantium. Nemo eligendi labore minus distinctio sit, et eveniet? Repellat, natus vero! Quo ea dicta tempore architecto, officia optio asperiores labore delectus odit dolorem soluta velit! Soluta dolorem, nisi harum consequuntur quis totam minus quibusdam nihil dignissimos, asperiores tenetur iure quod officia. Iure quod, quas fuga consectetur architecto asperiores fugiat nostrum recusandae explicabo et maiores! In consequuntur, excepturi tempore dolorum dolores similique dolorem architecto molestias illum ipsum soluta beatae rem ipsa possimus autem sapiente eveniet illo qui pariatur officia tempora? Incidunt omnis rerum vero necessitatibus assumenda quis totam, eligendi maxime rem. Nemo in quod fuga, expedita exercitationem natus, dolorem provident architecto, unde non quidem vitae harum cum eaque minus itaque nisi nobis tempore nam distinctio. Delectus aliquam repudiandae alias obcaecati est totam reiciendis error esse ipsum odit cum nesciunt, porro numquam reprehenderit doloribus pariatur voluptatem incidunt nam voluptates unde beatae ex aliquid sed. Mollitia harum commodi dolorum hic earum est impedit, temporibus laborum deserunt consequuntur error odio, laboriosam animi, id magnam nulla amet dicta! A totam eveniet iste numquam recusandae incidunt beatae praesentium eum similique ut, nemo magni ad facilis commodi, libero inventore molestias assumenda fugiat, odit officiis itaque architecto nostrum. Rem ex, maxime sint sequi dicta libero. Id voluptas deserunt inventore nemo, ratione cumque consectetur hic dolore impedit beatae a exercitationem debitis nihil dolorum eaque aspernatur est quidem ut dolores tempora distinctio. At libero similique, dolor sunt inventore vero expedita provident dolorum tempora quidem maiores quasi non veritatis neque eligendi corrupti illo unde magnam ab repellat corporis perferendis dignissimos laboriosam? Illo, quaerat alias. Corporis eos voluptatum expedita, dolor distinctio aliquid corrupti, earum, hic ad et magnam sit laudantium cumque ex ea ratione consequuntur placeat temporibus similique porro neque quo. Fugiat deleniti sint ipsam aliquid vero. Fuga natus similique, aut fugit modi voluptatem. Dignissimos hic alias cum architecto ex doloremque, consectetur distinctio voluptates reprehenderit expedita tempora, saepe repudiandae dolor! A consectetur fuga sequi magni porro! Necessitatibus distinctio eius exercitationem voluptates quidem similique rerum nostrum porro id iste odit libero optio non incidunt fugit facilis quas doloremque dolores, consequuntur amet nihil. Ipsam, rem ab reiciendis dolor hic veniam soluta in obcaecati minus velit illo id eveniet sequi placeat magnam voluptates reprehenderit quam quis asperiores facilis consequatur? Enim vitae, rem animi, veniam, omnis quisquam tenetur ratione modi minus corrupti blanditiis facilis.


        <div id={styles['section-1-wrapper']}>
          {/* entity character fix suggested by next build */}
          <p id={styles['about-me-short-desc']} className={`${descInView ? styles['desc-in-view'] : styles['desc-out-view']}`}>Hi, I&apos;m Clay. I&apos;m a web developer out of Northeast Ohio.</p>

          <div id={styles['social-quick-links']} ref={descRef}>
            {/* https://react-icons.github.io/react-icons */}
            <AiFillLinkedin id={styles['linked-in-social-quick-link']} className={styles['social-quick-link']} />
            <FaGithubSquare id={styles['github-social-quick-link']} className={styles['social-quick-link']} />
            <FaYoutubeSquare id={styles['youtube-social-quick-link']} className={styles['social-quick-link']} />
          </div>
        </div>

        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi, suscipit illum? Doloribus placeat obcaecati esse inventore doloremque ad in laborum, dolores vero enim velit nam! Consequatur excepturi illum laboriosam sapiente, vel mollitia ex laudantium architecto sed aliquam facilis rerum modi veniam repellat praesentium fugit ut. Repellat enim suscipit vero fuga vel expedita obcaecati. Nostrum veniam inventore eius, nobis quis dolorem doloribus ipsa vero quibusdam odit voluptates exercitationem et possimus ipsum, laudantium, velit neque voluptate impedit iste autem soluta optio odio quos? Minima sequi ullam, odio cumque saepe aspernatur unde ab blanditiis iste ducimus ad, deleniti cum vel tenetur. Esse laboriosam a illo expedita consequatur dignissimos. Dolores asperiores labore officiis quae rerum? Non temporibus error nostrum at repellat ipsum eum doloremque, quo accusamus, dolores in earum ex? Eius aperiam qui impedit exercitationem libero quos nulla corporis. Harum error accusantium ducimus ab qui? Sint natus omnis temporibus corrupti, culpa animi rem soluta nemo numquam recusandae voluptate reprehenderit voluptatibus. Sequi quas eveniet at saepe ipsum tempora explicabo nulla consequatur, necessitatibus asperiores dolorem accusantium autem esse, provident veritatis numquam maxime facilis perspiciatis aperiam. Voluptas, nemo voluptatibus totam veniam nobis labore quam. Cum totam maxime harum officiis, veritatis esse odit quasi excepturi exercitationem unde asperiores.
      </main>
      </>
  )
}
